import { useRef } from 'react';
import { motion, useInView } from 'framer-motion';
import { Link } from 'react-router-dom';

function ReportMockup() {
  return (
    <div
      style={{
        background: 'var(--bg-dark)',
        borderRadius: 'var(--r-card)',
        padding: 24,
        fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSize: 12.5,
        color: 'rgba(255,255,255,0.9)',
        lineHeight: 1.7,
        boxShadow: 'var(--sh-float)',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 14, paddingBottom: 12, borderBottom: '1px solid var(--bd-dark)' }}>
        <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#ff5f57' }} />
        <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#febc2e' }} />
        <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#28c840' }} />
        <span style={{ marginLeft: 12, color: 'var(--tx-muted-dark)', fontSize: 12 }}>CBN_MFB_Regulatory_Return_May2026.txt</span>
      </div>
      <div style={{ color: 'var(--tx-muted-dark)' }}>// Generated by RegCo AI — May 2026</div>
      <div>INSTITUTION: <span style={{ color: 'var(--ac-teal-dark)' }}>Nakdnx MFB Abuja</span></div>
      <div>REPORTING PERIOD: May 2026</div>
      <div>TOTAL ASSETS: ₦3,250,900,000</div>
      <div>CAR: 14.44% <span style={{ color: 'var(--ac-teal-dark)' }}>[PASS]</span></div>
      <div>LIQUIDITY: 55.27% <span style={{ color: 'var(--ac-teal-dark)' }}>[PASS]</span></div>
      <div>NPL: 4.00% <span style={{ color: 'var(--ac-teal-dark)' }}>[PASS]</span></div>
      <div style={{ marginTop: 12, color: 'var(--ac-teal-dark)' }}>✓ All ratios within CBN limits. Ready to submit.</div>
    </div>
  );
}

function AMLMockup() {
  const alerts = [
    { name: 'Emeka Okafor', amount: '₦6,500,000', type: 'CTR', severity: 'HIGH' },
    { name: 'Fatima Al-Hassan', amount: '₦4,750,000', type: 'STRUCTURING', severity: 'HIGH' },
    { name: 'Yusuf Ibrahim', amount: '₦12,000,000', type: 'VELOCITY', severity: 'CRITICAL' },
    { name: 'Aisha Musa', amount: '₦4,900,000', type: 'STRUCTURING', severity: 'HIGH' },
  ];
  const sev = (s: string) => (s === 'CRITICAL' ? '#c44a4a' : '#d97706');

  return (
    <div
      style={{
        background: '#fff',
        borderRadius: 'var(--r-card)',
        border: '1px solid var(--bd-light)',
        boxShadow: 'var(--sh-float)',
        overflow: 'hidden',
      }}
    >
      <div
        style={{
          padding: '16px 20px',
          borderBottom: '1px solid var(--bd-light)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span
            style={{
              width: 8,
              height: 8,
              borderRadius: '50%',
              background: '#c44a4a',
              boxShadow: '0 0 0 4px rgba(196,74,74,0.18)',
            }}
          />
          <span style={{ fontWeight: 600, color: 'var(--tx-primary)', fontSize: 14 }}>Live Transaction Monitor</span>
        </div>
        <span style={{ fontSize: 11, color: 'var(--tx-muted)', fontWeight: 500 }}>4 NEW</span>
      </div>
      <div>
        {alerts.map((a, i) => (
          <div
            key={i}
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '14px 20px',
              borderBottom: i < alerts.length - 1 ? '1px solid var(--bd-light)' : 'none',
            }}
          >
            <div>
              <div style={{ fontSize: 13.5, fontWeight: 600, color: 'var(--tx-primary)' }}>{a.name}</div>
              <div style={{ fontSize: 12, color: 'var(--tx-muted)', marginTop: 2 }}>
                {a.amount} · {a.type}
              </div>
            </div>
            <span
              style={{
                fontSize: 10.5,
                fontWeight: 700,
                color: sev(a.severity),
                background: `${sev(a.severity)}15`,
                padding: '4px 8px',
                borderRadius: 4,
                letterSpacing: 0.5,
              }}
            >
              {a.severity}
            </span>
          </div>
        ))}
      </div>
      <div style={{ display: 'flex', padding: 12, gap: 8, background: 'var(--bg-page)' }}>
        <button
          style={{
            flex: 1,
            fontSize: 12.5,
            fontWeight: 600,
            color: 'var(--tx-primary)',
            background: '#fff',
            border: '1px solid var(--bd-light)',
            borderRadius: 6,
            padding: '8px 12px',
            cursor: 'pointer',
          }}
        >
          Review All
        </button>
        <button
          style={{
            flex: 1,
            fontSize: 12.5,
            fontWeight: 600,
            color: '#fff',
            background: 'var(--tx-primary)',
            border: 'none',
            borderRadius: 6,
            padding: '8px 12px',
            cursor: 'pointer',
          }}
        >
          File STR →
        </button>
      </div>
    </div>
  );
}

const FLOWS = [
  {
    tag: 'REPORT GENERATION',
    heading: 'Generate any return in under 5 minutes.',
    body: "Upload your CBS export. RegCo's AI reads every account category, maps it to the correct regulatory template, validates all ratios, and produces a submission-ready text file. Works with FlexCube, Ncube, Finacle, Temenos — any format.",
    cta: 'See all 17 returns',
    ctaLink: '/blog/compliance-guide',
    mockup: <ReportMockup />,
  },
  {
    tag: 'AML MONITORING',
    heading: 'Flag suspicious transactions automatically.',
    body: 'Six AML detection rules run on every transaction batch: CTR (₦5M+), structuring patterns, velocity anomalies, round-figure screening, PEP matching, and sanctions hits. Alerts escalate to STR queue with one click.',
    cta: 'How AML monitoring works',
    ctaLink: '/blog/compliance-guide',
    mockup: <AMLMockup />,
  },
];

function Flow({ flow, reversed }: { flow: typeof FLOWS[0]; reversed: boolean }) {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: '-80px' });

  return (
    <div
      ref={ref}
      style={{
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: 80,
        alignItems: 'center',
        padding: '80px 0',
      }}
    >
      <motion.div
        initial={{ opacity: 0, x: reversed ? 30 : -30 }}
        animate={inView ? { opacity: 1, x: 0 } : {}}
        transition={{ duration: 0.7 }}
        style={{ order: reversed ? 2 : 1 }}
      >
        <div style={{ fontSize: 12, fontWeight: 600, letterSpacing: 2, color: 'var(--ac-teal)', marginBottom: 16 }}>
          {flow.tag}
        </div>
        <h3
          style={{
            fontFamily: 'var(--font-head)',
            fontSize: 'clamp(28px, 3.4vw, 42px)',
            fontWeight: 600,
            lineHeight: 1.1,
            letterSpacing: '-1px',
            color: 'var(--tx-primary)',
            marginBottom: 20,
          }}
        >
          {flow.heading}
        </h3>
        <p style={{ fontSize: 16, lineHeight: 1.6, color: 'var(--tx-secondary)', marginBottom: 24 }}>{flow.body}</p>
        <Link
          to={flow.ctaLink}
          style={{
            fontSize: 14,
            fontWeight: 600,
            color: 'var(--ac-teal)',
            textDecoration: 'none',
            display: 'inline-flex',
            alignItems: 'center',
            gap: 4,
          }}
        >
          {flow.cta} ›
        </Link>
      </motion.div>
      <motion.div
        initial={{ opacity: 0, x: reversed ? -30 : 30 }}
        animate={inView ? { opacity: 1, x: 0 } : {}}
        transition={{ duration: 0.7, delay: 0.15 }}
        style={{ order: reversed ? 1 : 2 }}
      >
        {flow.mockup}
      </motion.div>
    </div>
  );
}

export function InteractiveFlowsSection() {
  return (
    <section style={{ background: 'var(--bg-page)', padding: '40px 32px' }}>
      <div style={{ maxWidth: 1240, margin: '0 auto' }}>
        {FLOWS.map((f, i) => (
          <Flow key={i} flow={f} reversed={i % 2 === 1} />
        ))}
      </div>
    </section>
  );
}

export default InteractiveFlowsSection;
