 {/* Top launch pricing bar - exact 36px height */}
  <div style={{ backgroundColor: '#FFFFFF', borderBottomColor: '#0000001A', borderBottomStyle: 'solid', borderBottomWidth: '1px', boxSizing: 'border-box', position: 'relative', left: '0px', right: '0px', top: '0px' }}>
    <div style={{ alignItems: 'center', boxSizing: 'border-box', display: 'flex', height: '36px', justifyContent: 'center', marginLeft: 'auto', marginRight: 'auto', maxWidth: '1280px', paddingInline: '16px' }}>
      <div style={{ boxSizing: 'border-box', color: '#111', display: 'flex', fontFamily: '"Geist", system-ui, sans-serif', fontFeatureSettings: '"cv01", "ss02"', fontSize: '14px', fontWeight: 500, lineHeight: '150%', textAlign: 'center' }}>Limited-time launch pricing</div>
      <div style={{ boxSizing: 'border-box', color: '#000000A6', display: 'flex', fontFamily: '"Geist", system-ui, sans-serif', fontFeatureSettings: '"cv01", "ss01", "ss02"', fontSize: '14px', lineHeight: '137.5%', marginLeft: '6px', textAlign: 'center' }}>Pro $29/mo $49 · Max $69/mo $99</div>
    </div>
  </div>

  {/* Hidden accessibility clip - preserved */}
  <div style={{ boxSizing: 'border-box', position: 'absolute', width: '0px', height: '0px', overflow: 'hidden' }}>
    <div style={{ boxSizing: 'border-box', clip: 'rect(0px, 0px)', height: '1px', width: '1px', margin: '-1px', overflow: 'hidden', position: 'absolute' }} />
  </div>

  {/* Right rail Merlin widgets - original opacity 0, translate 8px 0px, preserved but hidden */}
  <div style={{ alignItems: 'flex-end', boxSizing: 'border-box', display: 'flex', flexDirection: 'column', gap: '6px', position: 'absolute', right: '0px', top: '610.5px', zIndex: 20, pointerEvents: 'none' }}>
    <div style={{ alignItems: 'flex-end', boxSizing: 'border-box', display: 'flex', flexDirection: 'column', gap: '2px', opacity: 0, position: 'relative', transform: 'translate(8px, 0px)' }}>
      <div style={{ alignItems: 'center', backgroundColor: '#1C1C1E', borderBottomLeftRadius: '10px', borderTopLeftRadius: '10px', boxShadow: '#FFFFFF0F 0px 0px 0px 1px inset, #00000066 -2px 1px 8px, #00000033 0px 1px 2px', boxSizing: 'border-box', display: 'flex', height: '36px', width: '36px', justifyContent: 'center' }}>
        <svg width="18" height="18" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style={{ height: '18px', width: '18px' }}><circle cx="12" cy="12" r="10" fill="none" stroke="#A1A1AA" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /><path d="M2 12h20" fill="none" stroke="#A1A1AA" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /><path d="M12 2a15.3 15.3 0 0 1 4 10a15.3 0 0 1-4 10a15.3 15.3 0 0 1-4-10a15.3 0 0 1 4-10z" fill="none" stroke="#A1A1AA" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /></svg>
      </div>
    <div style={{ alignItems: 'center', backgroundColor: '#1C1C1E', borderBottomLeftRadius: '10px', borderTopLeftRadius: '10px', boxShadow: '#FFFFFF0F 0px 0px 0px 1px inset, #00000080 -3px 2px 14px, #0000004D 0px 1px 4px', boxSizing: 'border-box', display: 'flex', opacity: 0.55, padding: '8px', position: 'relative' }}>
      <div style={{ backgroundColor: '#DDD', borderRadius: '1px', boxSizing: 'border-box', height: '24px', width: '24px', outline: '1px solid #FFFFFF1A', outlineOffset: '-1px', overflow: 'hidden' }} />
    </div>
  </div>

  {/* Nav - exact blur 24px saturate 150%, bg #0D0C0A73, height 56px, maxWidth 1280px, paddingInline 24px, gap 48px */}
  <div style={{ backdropFilter: 'blur(24px) saturate(150%)', backgroundColor: '#0D0C0A73', boxSizing: 'border-box', position: 'sticky', top: '0px', zIndex: 50, borderBottom: '1px solid rgba(255,255,255,0.07)' }}>
    <div style={{ alignItems: 'center', boxSizing: 'border-box', display: 'grid', gap: '48px', gridTemplateColumns: 'minmax(0px, 1fr) auto minmax(0px, 1fr)', height: '56px', marginLeft: 'auto', marginRight: 'auto', maxWidth: '1280px', paddingInline: '24px' }}>
      <div style={{ justifySelf: 'flex-start' }}><div style={{ backgroundImage: 'url(https://app.paper.design/file-assets/01KWCRWTX4FYZH5GEAGHH0B512/2SJTXX1X8J2Z632KPK106GM3T4.png)', backgroundPosition: '-12.1469px -43.6351px', backgroundRepeat: 'no-repeat', backgroundSize: '104.265px 104.265px', display: 'inline-block', height: '22px', width: '82px' }} /></div>
      <div style={{ alignItems: 'center', display: 'flex', gap: '28px', justifySelf: 'center' }}>
        <div style={{ color: '#FFFFFF', fontFamily: '"Geist", system-ui, sans-serif', fontFeatureSettings: '"cv01", "ss01", "ss02"', fontSize: '15px', lineHeight: '150%' }}>Work</div>
        <div style={{ color: '#FFFFFF', fontFamily: '"Geist", system-ui, sans-serif', fontFeatureSettings: '"cv01", "ss01", "ss02"', fontSize: '15px', lineHeight: '150%' }}>Pricing</div>
        <div style={{ color: '#FFFFFF', fontFamily: '"Geist", system-ui, sans-serif', fontFeatureSettings: '"cv01", "ss01", "ss02"', fontSize: '15px', lineHeight: '150%' }}>Docs</div>
        <div style={{ color: '#FFFFFF', fontFamily: '"Geist", system-ui, sans-serif', fontFeatureSettings: '"cv01", "ss02"', fontSize: '15px', lineHeight: '150%' }}>Blog</div>
      </div>
      <div style={{ alignItems: 'center', display: 'flex', gap: '10px', justifyContent: 'flex-end', justifySelf: 'flex-end', paddingLeft: '16px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '6px', padding: '2px' }}><svg viewBox="0 0 24 24" width="14" height="14"><path d="M20.317 4.37a19.791 19.791 0 00-4.885-1.515" fill="#FFFFFF" /></svg></div>
        <div style={{ display: 'flex', backgroundColor: '#000000', borderRadius: '9999px', height: '28px', paddingInline: '10px', gap: '6px', alignItems: 'center' }}><div style={{ backgroundColor: '#FFFFFF', borderRadius: '9999px', height: '16px', width: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><span style={{ fontSize: '10px', color: '#000' }}>G</span></div><span style={{ color: '#FFFFFF', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '13px', fontWeight: 500 }}>9.8K</span></div>
        <div style={{ borderColor: '#FFFFFF40', borderStyle: 'solid', borderWidth: '1px', borderRadius: '9999px', height: '28px', paddingInline: '12px', display: 'flex', alignItems: 'center' }}><span style={{ color: '#FFFFFF', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '13px' }}>Book a demo</span></div>
        <div style={{ backgroundColor: '#FFFFFF', borderRadius: '9999px', height: '28px', paddingInline: '12px', display: 'flex', alignItems: 'center' }}><span style={{ color: '#0D0C0A', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '13px', fontWeight: 500 }}>Download</span></div>
      </div>
    </div>
  </div>

  {/* Hero wrapper maxWidth 1280 paddingInline 24 */}
  <div style={{ boxSizing: 'border-box', marginLeft: 'auto', marginRight: 'auto', maxWidth: '1280px', paddingInline: '24px', width: '100%' }}>
    <div style={{ paddingTop: '64px', paddingBottom: '40px' }}>
      <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px' }}>
        <span style={{ color: '#B3B3B3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '14px', lineHeight: '150%' }}>Backed by</span>
        <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><span style={{ height: '20px', width: '20px', backgroundImage: 'url(https://app.paper.design/file-assets/01KWCRWTX4FYZH5GEAGHH0B512/1W1CV0B01ZKBCP8MVY5P46E0J1.webp)', backgroundSize: 'cover', display: 'inline-block' }} /><span style={{ color: '#E85D04', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '14px', letterSpacing: '0.35px', lineHeight: '150%' }}>Combinator</span></span>
      </div>
      <div style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontFeatureSettings: '"cv01", "ss02"', fontSize: '60px', letterSpacing: '-1.8px', lineHeight: '110%', marginTop: '24px', maxWidth: '896px' }}>Compliance automation for banks that can't afford to miss a filing.</div>
      <div style={{ marginTop: '24px', maxWidth: '768px' }}><span style={{ color: '#ECECECBF', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '19px', lineHeight: '150%', whiteSpace: 'pre-wrap' }}>{'RegCo connects to your core banking system and handles' + '\n' + 'the compliance work your team does manually: screening' + '\n' + 'customers, generating returns, and keeping an audit trail.'}</span></div>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px', marginTop: '40px', paddingBottom: '20px', alignItems: 'center' }}>
        <div style={{ position: 'relative' }}>
          <div style={{ backgroundColor: '#ECECEC', borderRadius: '9999px', display: 'inline-flex', gap: '8px', paddingBlock: '10px', paddingInline: '16px', alignItems: 'center' }}><span style={{ color: '#0D0C0A', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '15px', fontWeight: 500, lineHeight: '150%' }}>Book a demo</span></div>
          <div style={{ color: '#B3B3B3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '12px', lineHeight: '150%', marginTop: '6px', position: 'absolute', left: '50%', top: '100%', transform: 'translateX(-50%)', whiteSpace: 'nowrap' }}>Minimum macOS 26 (Tahoe)</div>
        </div>
        <div style={{ backgroundColor: '#FFFFFF14', borderRadius: '9999px', paddingBlock: '10px', paddingInline: '16px', display: 'flex' }}><span style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '15px', lineHeight: '150%' }}>Login</span></div>
      </div>
    </div>

    {/* Hero media - exact borderRadius 16px overflow clip */}
    <div style={{ paddingBottom: '40px', paddingTop: '16px' }}><div style={{ borderRadius: '16px', overflow: 'hidden', position: 'relative', backgroundColor: '#151410', border: '1px solid rgba(255,255,255,0.08)' }}><div style={{ aspectRatio: '16 / 9', width: '100%', backgroundColor: '#1A1917' }} /><div style={{ position: 'absolute', right: '16px', top: '16px' }}><div style={{ backdropFilter: 'blur(8px)', backgroundColor: '#00000080', borderRadius: '6px', display: 'inline-flex', height: '32px', width: '32px', alignItems: 'center', justifyContent: 'center' }}><svg viewBox="0 0 24 24" width="16" height="16"><path d="M11 5L6 9H3v6h3l5 4V5z M16 9l5 5 M21 9l-5 5" fill="none" stroke="rgba(255,255,255,0.85)" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" /></svg></div></div></div></div>

    {/* Integrations - exact columnGap 32px rowGap 16px */}
    <div style={{ paddingBlock: '56px' }}>
      <div style={{ color: '#B3B3B3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '15px', lineHeight: '150%', display: 'flex', justifyContent: 'center', marginBottom: '40px' }}>Built to integrate with</div>
      <div style={{ display: 'flex', flexWrap: 'wrap', columnGap: '32px', rowGap: '16px', justifyContent: 'center', maxWidth: '1280px', marginLeft: 'auto', marginRight: 'auto', paddingInline: '24px', alignItems: 'flex-end' }}>
        <div style={{ display: 'flex', gap: '10px', alignItems: 'flex-end' }}><span style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '24px', letterSpacing: '-0.6px', lineHeight: '133.333%' }}>Dojah</span><span style={{ color: '#B3B3B3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '15px', lineHeight: '150%', marginBottom: '2px' }}>Identity verification</span></div>
        <div style={{ display: 'flex', gap: '10px', alignItems: 'flex-end' }}><span style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '24px', letterSpacing: '-0.6px', lineHeight: '133.333%' }}>Smile Identity</span><span style={{ color: '#B3B3B3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '15px', lineHeight: '150%', marginBottom: '2px' }}>KYC and liveness checks</span></div>
        <div style={{ display: 'flex', gap: '10px', alignItems: 'flex-end' }}><span style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '24px', letterSpacing: '-0.6px', lineHeight: '133.333%' }}>Prembly</span><span style={{ color: '#B3B3B3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '15px', lineHeight: '150%', marginBottom: '2px' }}>NIN and document verification</span></div>
        <div style={{ display: 'flex', gap: '10px', alignItems: 'flex-end' }}><span style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '24px', letterSpacing: '-0.6px', lineHeight: '133.333%' }}>NIBSS</span><span style={{ color: '#B3B3B3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '15px', lineHeight: '150%', marginBottom: '2px' }}>— BVN infrastructure</span></div>
        <span style={{ color: '#B3B3B399', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '15px', lineHeight: '150%', marginBottom: '2px' }}>and more</span>
      </div>
    </div>
  </div>

  {/* Feature 1 - grid minmax 300px 1fr gap 56px */}
  <div style={{ paddingBlock: '96px', maxWidth: '1280px', marginLeft: 'auto', marginRight: 'auto', paddingInline: '24px', display: 'grid', gridTemplateColumns: 'minmax(0px, 300px) 1fr', gap: '56px', alignItems: 'center' }}>
    <div style={{ maxWidth: '300px' }}><div style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '36px', letterSpacing: '-0.72px', lineHeight: '120%' }}>Screen without leaving the dashboard</div><div style={{ color: '#ECECECB3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '17px', lineHeight: '155%', marginTop: '16px' }}>Stop exporting transaction data to a separate tool and re-importing flags. Screen, score, and review every transaction directly inside RegCo.</div><div style={{ display: 'inline-flex', gap: '4px', marginTop: '28px', alignItems: 'center' }}><span style={{ color: '#E63535', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '16px', lineHeight: '150%' }}>Learn more</span><span style={{ color: '#E63535', fontSize: '16px' }}>→</span></div></div>
    <div style={{ borderRadius: '16px', overflow: 'hidden', backgroundColor: '#1A1917', aspectRatio: '16 / 10' }} />
  </div>

  {/* Feature 2 - grid 1fr 360px with blur background */}
  <div style={{ paddingBlock: '96px', maxWidth: '1280px', marginLeft: 'auto', marginRight: 'auto', paddingInline: '24px', display: 'grid', gridTemplateColumns: '1fr minmax(0px, 360px)', gap: '56px', alignItems: 'center' }}>
    <div style={{ borderRadius: '16px', overflow: 'hidden', position: 'relative' }}><div style={{ position: 'absolute', inset: '0px', backgroundImage: 'url(https://app.paper.design/file-assets/01KWCRWTX4FYZH5GEAGHH0B512/54X6V3Q435WABTR4AYCDC8VAKZ.webp)', backgroundSize: 'cover', filter: 'blur(5px)', opacity: 0.6 }} /><div style={{ position: 'relative', paddingBlock: '28px', paddingInline: '16px' }}><div style={{ aspectRatio: '1024 / 671', backgroundImage: 'url(https://app.paper.design/file-assets/01KWCRWTX4FYZH5GEAGHH0B512/6Q11AGXRT4265FY41XTRNGSYEJ.webp)', backgroundSize: 'cover', backgroundPosition: '50%', borderRadius: '10px', width: '100%' }} /></div></div>
    <div style={{ maxWidth: '360px' }}><div style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '36px', letterSpacing: '-0.72px', lineHeight: '120%' }}>A complete compliance workspace</div><div style={{ marginTop: '16px' }}><div style={{ display: 'flex', gap: '12px', marginBottom: '12px' }}><span style={{ backgroundColor: '#ECECEC59', borderRadius: '9999px', height: '6px', width: '6px', marginTop: '8px', flexShrink: 0 }} /><span style={{ color: '#ECECECB3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '16px', lineHeight: '150%' }}>Transaction monitoring</span></div><div style={{ display: 'flex', gap: '12px', marginBottom: '12px' }}><span style={{ backgroundColor: '#ECECEC59', borderRadius: '9999px', height: '6px', width: '6px', marginTop: '8px', flexShrink: 0 }} /><span style={{ color: '#ECECECB3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '16px', lineHeight: '150%' }}>Screening, and case management in one view</span></div><div style={{ display: 'flex', gap: '12px', marginBottom: '12px' }}><span style={{ backgroundColor: '#ECECEC59', borderRadius: '9999px', height: '6px', width: '6px', marginTop: '8px', flexShrink: 0 }} /><span style={{ color: '#ECECECB3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '16px', lineHeight: '150%' }}>Filter, flag, escalate, and close cases from a single record</span></div><div style={{ display: 'flex', gap: '12px' }}><span style={{ backgroundColor: '#ECECEC59', borderRadius: '9999px', height: '6px', width: '6px', marginTop: '8px', flexShrink: 0 }} /><span style={{ color: '#ECECECB3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '16px', lineHeight: '150%' }}>Export CTR and STR filings in CBN and NFIU format when you need to</span></div></div><div style={{ display: 'inline-flex', gap: '4px', marginTop: '28px' }}><span style={{ color: '#E63535', fontSize: '16px' }}>Learn more</span><span style={{ color: '#E63535' }}>→</span></div></div>
  </div>

  {/* Feature 3 */}
  <div style={{ paddingBlock: '96px', maxWidth: '1280px', marginLeft: 'auto', marginRight: 'auto', paddingInline: '24px', display: 'grid', gridTemplateColumns: 'minmax(0px, 360px) 1fr', gap: '56px', alignItems: 'center' }}>
    <div style={{ maxWidth: '360px' }}><div style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '36px', letterSpacing: '-0.72px', lineHeight: '120%' }}>Connect your systems</div><div style={{ color: '#ECECECB3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '17px', lineHeight: '155%', marginTop: '16px', whiteSpace: 'pre-wrap' }}>{'Via a signed webhook, connect your core banking system and have every transaction screened and scored the moment it happens no manual export, no batch upload.'}</div><div style={{ display: 'inline-flex', gap: '4px', marginTop: '28px' }}><span style={{ color: '#E63535', fontSize: '16px' }}>Learn how it works</span><span style={{ color: '#E63535' }}>→</span></div></div>
    <div style={{ borderRadius: '16px', overflow: 'hidden', backgroundColor: '#1A1917', aspectRatio: '16 / 10' }} />
  </div>

  {/* Compliance layer - bg #161614 borderTop #FFFFFF12 */}
  <div style={{ backgroundColor: '#161614', borderTop: '1px solid #FFFFFF12', paddingBlock: '96px' }}><div style={{ maxWidth: '1280px', marginLeft: 'auto', marginRight: 'auto', paddingInline: '24px' }}><div style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '40px', letterSpacing: '-0.8px', lineHeight: '115%', display: 'flex', justifyContent: 'center', textAlign: 'center' }}>RegCo is building the compliance layer for regulated institutions.</div><div style={{ borderRadius: '16px', marginLeft: 'auto', marginRight: 'auto', marginTop: '48px', maxWidth: '896px', overflow: 'hidden' }}><div style={{ aspectRatio: '1024 / 573', backgroundImage: 'url(https://app.paper.design/file-assets/01KWCRWTX4FYZH5GEAGHH0B512/68065B772N5SVH0TEJZC21TDGZ.webp)', backgroundSize: 'cover', backgroundPosition: '50%', width: '100%' }} /></div></div></div>

  {/* FAQ - bg #1E1E1C */}
  <div style={{ backgroundColor: '#1E1E1C', borderTop: '1px solid #FFFFFF12', paddingBlock: '96px' }}><div style={{ maxWidth: '768px', marginLeft: 'auto', marginRight: 'auto', paddingInline: '24px' }}><div style={{ color: '#B3B3B3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '15px', lineHeight: '150%', display: 'flex', justifyContent: 'center' }}>FAQ</div><div style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '36px', letterSpacing: '-0.72px', lineHeight: '115%', display: 'flex', justifyContent: 'center', marginTop: '12px', textAlign: 'center' }}>Common questions</div><div style={{ borderTop: '1px solid #FFFFFF12', marginTop: '40px' }}>{['How is RegCo different from a manual compliance process?','How is this different from building compliance tooling in-house?','How does pricing work?','How does the CBS connection work?','Can I use RegCo alongside our existing KYC and screening tools?','Do you train AI models on our transaction data?','What reports can I export?','Do you offer enterprise plans?'].map(function(q, idx) { return (<div key={q} style={{ borderBottom: '1px solid #FFFFFF12' }}><div onClick={function(){ toggleFaq(idx); }} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '16px', paddingBlock: '20px', cursor: 'pointer' }}><span style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '17px', lineHeight: '150%' }}>{q}</span><svg viewBox="0 0 16 16" width="16" height="16" style={{ transform: openFaq === idx? 'rotate(180deg)' : 'rotate(0deg)', transition: 'transform 0.2s' }}><path d="M4 6l4 4 4-4" fill="none" stroke="#B3B3B3" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg></div>{openFaq === idx? <div style={{ paddingBottom: '20px', color: '#ECECECB3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '15px', lineHeight: '160%' }}>Deterministic proof: every flag maps to SQL and CBN regulation section. No black box AI decision. Audit trail with maker checker and GoAML XML export.</div> : null}</div>); })}</div></div></div>

  {/* Final CTA */}
  <div style={{ borderTop: '1px solid #FFFFFF12', paddingBlock: '96px', textAlign: 'center' }}><div style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '40px', letterSpacing: '-0.8px', lineHeight: '150%' }}>See RegCo on your institution.</div><div style={{ display: 'flex', gap: '10px', justifyContent: 'center', marginTop: '32px', paddingBottom: '20px' }}><div style={{ backgroundColor: '#ECECEC', borderRadius: '9999px', paddingBlock: '10px', paddingInline: '16px' }}><span style={{ color: '#0D0C0A', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '15px', fontWeight: 500 }}>Book a demo</span></div><div style={{ backgroundColor: '#FFFFFF14', borderRadius: '9999px', paddingBlock: '10px', paddingInline: '16px' }}><span style={{ color: '#ECECEC', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '15px' }}>Log in</span></div></div></div>

  <div style={{ borderTop: '1px solid #FFFFFF12', paddingBlock: '48px', paddingInline: '24px', maxWidth: '1280px', marginLeft: 'auto', marginRight: 'auto', width: '100%', display: 'flex', justifyContent: 'space-between', gap: '40px', flexWrap: 'wrap' }}>
    <div style={{ maxWidth: '200px' }}><div style={{ backgroundImage: 'url(https://app.paper.design/file-assets/01KWCRWTX4FYZH5GEAGHH0B512/2SJTXX1X8J2Z632KPK106GM3T4.png)', backgroundPosition: '-12.1469px -43.6351px', backgroundSize: '104.265px 104.265px', height: '22px', width: '82px' }} /><div style={{ color: '#B3B3B3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '14px', lineHeight: '137.5%', marginTop: '10px' }}>The compliance infrastructure for Nigerian banks.</div><div style={{ color: '#B3B3B3B3', fontFamily: '"Geist", system-ui, sans-serif', fontSize: '13px', lineHeight: '150%', marginTop: '10px' }}>© 2026 RegCo, Inc.</div></div>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0px, 1fr))', columnGap: '64px', rowGap: '32px' }}>
      <div><div style={{ color: '#ECECEC', fontSize: '15px', fontWeight: 500, marginBottom: '12px' }}>Product</div><div style={{ color: '#B3B3B3', fontSize: '15px', marginBottom: '10px' }}>Pricing</div><div style={{ color: '#B3B3B3', fontSize: '15px' }}>Docs</div></div>
      <div><div style={{ color: '#ECECEC', fontSize: '15px', fontWeight: 500, marginBottom: '12px' }}>Company</div><div style={{ color: '#B3B3B3', fontSize: '15px', marginBottom: '10px' }}>Work</div><div style={{ color: '#B3B3B3', fontSize: '15px' }}>About</div></div>
      <div><div style={{ color: '#ECECEC', fontSize: '15px', fontWeight: 500, marginBottom: '12px' }}>Legal</div><div style={{ color: '#B3B3B3', fontSize: '15px', marginBottom: '10px' }}>Privacy</div><div style={{ color: '#B3B3B3', fontSize: '15px' }}>Terms</div></div>
      <div><div style={{ color: '#ECECEC', fontSize: '15px', fontWeight: 500, marginBottom: '12px' }}>Connect</div><div style={{ color: '#B3B3B3', fontSize: '15px' }}>GitHub 9.8K</div></div>
    </div>
  </div>
</div>
);
}
