import { supabase } from '@/integrations/supabase/client';

export interface ReportData {
  id?: string;
  report_name?: string;
  report_type?: string;
  regulator?: string;
  report_url?: string;
  file_url?: string;
  file_path?: string;
  report_filename?: string;
  generated_at?: string;
  validation_passed?: boolean;
  car_percentage?: number | null;
  liquidity_percentage?: number | null;
  npl_ratio?: number | null;
  status?: string;
  user_id?: string;
}

const buildFileName = (report: ReportData): string => {
  if (report.report_filename) return report.report_filename;
  const type = (report.report_type || report.report_name || 'Report').replace(/\s+/g, '_');
  const reg = report.regulator || 'CBN';
  const date = new Date().toISOString().slice(0, 10);
  return `RegCo_${type}_${reg}_${date}.txt`;
};

const triggerBrowserDownload = (content: Blob | string, fileName: string): void => {
  const blob = typeof content === 'string'
    ? new Blob([content], { type: 'text/plain;charset=utf-8' })
    : new Blob([content], { type: 'text/plain;charset=utf-8' });
  const safeName = fileName.endsWith('.txt') ? fileName : fileName.replace(/\.[^.]+$/, '') + '.txt';
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = safeName;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};

const isBinaryZipBlob = async (blob: Blob): Promise<boolean> => {
  try {
    const buf = await blob.slice(0, 4).arrayBuffer();
    const b = new Uint8Array(buf);
    return b[0] === 0x50 && b[1] === 0x4b; // "PK" — zip/docx header
  } catch { return false; }
};

const buildFallbackContent = (report: ReportData): string => {
  const date = report.generated_at
    ? new Date(report.generated_at).toLocaleDateString('en-NG', { day: 'numeric', month: 'long', year: 'numeric' })
    : new Date().toLocaleDateString('en-NG', { day: 'numeric', month: 'long', year: 'numeric' });

  return `CENTRAL BANK OF NIGERIA
MICROFINANCE BANK REGULATORY RETURN
=====================================

Report Type:             ${report.report_type || 'N/A'}
Regulator:               ${report.regulator || 'CBN'}
Generated:               ${date}
Status:                  ${report.status || 'ready'}

VALIDATION RESULTS
==================
Validation Passed:       ${report.validation_passed ? 'YES \u2713' : 'NO \u2717'}
Capital Adequacy Ratio:  ${report.car_percentage != null ? report.car_percentage + '%' : 'N/A'}
Liquidity Ratio:         ${report.liquidity_percentage != null ? report.liquidity_percentage + '%' : 'N/A'}
NPL Ratio:               ${report.npl_ratio != null ? report.npl_ratio + '%' : 'N/A'}

=====================================
Generated by RegCo Technologies Limited
Automated Regulatory Reporting Platform
Contact: support@regco.com.ng
=====================================`;
};

const tryStorageDownload = async (bucket: string, path: string): Promise<Blob | null> => {
  try {
    const { data, error } = await supabase.storage.from(bucket).download(path);
    if (!error && data) return data;
  } catch (e) {
    console.warn('Storage download failed:', e);
  }
  return null;
};

export const downloadReport = async (
  report: ReportData,
  onStart?: () => void,
  onComplete?: () => void,
  onError?: (error: string) => void,
): Promise<void> => {
  onStart?.();
  const fileName = buildFileName(report);
  const fileUrl = report.report_url || report.file_url;

  // METHOD 1 — full public URL: extract bucket + path and use SDK
  if (fileUrl && fileUrl.includes('/storage/v1/object/')) {
    const afterPublic =
      fileUrl.split('/storage/v1/object/public/')[1] ||
      fileUrl.split('/storage/v1/object/')[1];
    if (afterPublic) {
      const parts = afterPublic.replace(/^sign\//, '').split('/');
      const bucket = parts[0];
      const filePath = parts.slice(1).join('/').split('?')[0];
      const blob = await tryStorageDownload(bucket, filePath);
      if (blob) {
        triggerBrowserDownload(blob, fileName);
        onComplete?.();
        return;
      }
    }
  }

  // METHOD 2 — value stored is a raw storage path (no protocol)
  const rawPath = (!fileUrl || !/^https?:\/\//i.test(fileUrl)) ? (fileUrl || report.file_path) : report.file_path;
  if (rawPath) {
    const blob = await tryStorageDownload('reports', rawPath);
    if (blob) {
      triggerBrowserDownload(blob, fileName);
      onComplete?.();
      return;
    }
  }

  // METHOD 3 — direct fetch from URL
  if (fileUrl && /^https?:\/\//i.test(fileUrl)) {
    try {
      const response = await fetch(fileUrl, { mode: 'cors' });
      if (response.ok) {
        const blob = await response.blob();
        triggerBrowserDownload(blob, fileName);
        onComplete?.();
        return;
      }
    } catch (e) {
      console.warn('Direct fetch failed:', e);
    }
  }

  // METHOD 4 — refresh from DB and retry once
  if (report.id) {
    try {
      const { data: fresh } = await supabase
        .from('reports')
        .select('*')
        .eq('id', report.id)
        .single();
      if (fresh) {
        const freshUrl = (fresh as any).report_url || (fresh as any).file_url;
        const freshPath = (fresh as any).file_path;
        if (freshPath) {
          const blob = await tryStorageDownload('reports', freshPath);
          if (blob) { triggerBrowserDownload(blob, fileName); onComplete?.(); return; }
        }
        if (freshUrl && /^https?:\/\//i.test(freshUrl)) {
          const r = await fetch(freshUrl, { mode: 'cors' });
          if (r.ok) { triggerBrowserDownload(await r.blob(), fileName); onComplete?.(); return; }
        }
      }
    } catch (e) {
      console.warn('DB refresh failed:', e);
    }
  }

  // METHOD 5 — synthesize fallback from metadata
  try {
    const content = buildFallbackContent(report);
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    triggerBrowserDownload(blob, fileName);
    onComplete?.();
  } catch (e: any) {
    onError?.(e?.message || 'Download failed');
  }
};
