INSERT INTO public.reports (user_id, status, report_type, generated_at, validation_passed, car_percentage, liquidity_percentage, npl_ratio, report_filename, content, report_name)
VALUES
('ea7dd158-eba4-4848-9caa-d787c187d8be','ready','MFB Regulatory Return',NOW()-INTERVAL '2 days',true,14.4,55.3,4.0,'RegCo_MFB_May2026.txt',
'CENTRAL BANK OF NIGERIA
MFB REGULATORY RETURN — MAY 2026
INSTITUTION: NAKDNX MFB LIMITED
=======================================
TOTAL ASSETS NET: NGN 3,250,900,000
CAR: 14.44% (Min 10%) PASS
LIQUIDITY: 55.27% (Min 20%) PASS
NPL: 4.00% (Max 5%) PASS
=======================================
Generated by RegCo Technologies Limited','CBN MFB Regulatory Return — May 2026'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','ready','VAT Return',NOW()-INTERVAL '5 days',true,null,null,null,'RegCo_VAT_May2026.txt',
'FIRS VAT RETURN — MAY 2026
NAKDNX MFB LIMITED
=======================================
Output VAT: NGN 6,555,000
Input VAT: NGN 1,785,000
NET VAT PAYABLE: NGN 4,770,000
Receipt: FIRS/VAT/2026/05/089234
=======================================
Generated by RegCo Technologies Limited','FIRS VAT Return — May 2026'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','ready','PAYE Remittance',NOW()-INTERVAL '5 days',true,null,null,null,'RegCo_PAYE_May2026.txt',
'FIRS PAYE REMITTANCE — MAY 2026
NAKDNX MFB LIMITED — 47 EMPLOYEES
=======================================
Gross Salaries: NGN 34,200,000
PAYE Deducted: NGN 5,406,815
=======================================
Generated by RegCo Technologies Limited','FIRS PAYE Remittance — May 2026'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','ready','AML/CFT Compliance Report',NOW()-INTERVAL '8 days',true,null,null,null,'RegCo_AMLCFT_Q1_2026.txt',
'NFIU AML/CFT COMPLIANCE REPORT — Q1 2026
NAKDNX MFB LIMITED
=======================================
Transactions Monitored: 14,847
STRs Filed: 3 | CTRs Filed: 28
KYC Complete: 128/143 (89.5%)
=======================================
Generated by RegCo Technologies Limited','NFIU AML/CFT Compliance — Q1 2026'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','ready','NDIC Premium Return',NOW()-INTERVAL '10 days',true,null,null,null,'RegCo_NDIC_Premium_2025.txt',
'NDIC ANNUAL PREMIUM RETURN — 2025
NAKDNX MFB LIMITED
=======================================
Total Insured Deposits: NGN 2,200,000,000
Premium Rate: 0.40%
PREMIUM PAYABLE: NGN 8,800,000
=======================================
Generated by RegCo Technologies Limited','NDIC Annual Premium Return — 2025'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','ready','SCUML Annual Compliance',NOW()-INTERVAL '15 days',true,null,null,null,'RegCo_SCUML_2025.txt',
'SCUML ANNUAL COMPLIANCE REPORT — 2025
NAKDNX MFB LIMITED
=======================================
KYC Complete: 7,963/8,847 (90%)
STRs Filed: 11 | CTRs: 94
Staff Trained: 41 | Hours: 112
=======================================
Generated by RegCo Technologies Limited','SCUML Annual Compliance — 2025'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','ready','WHT Return',NOW()-INTERVAL '6 days',true,null,null,null,'RegCo_WHT_May2026.txt',
'FIRS WHT RETURN — MAY 2026
NAKDNX MFB LIMITED
=======================================
Total Gross Payments: NGN 7,570,000
Total WHT Deducted: NGN 658,500
=======================================
Generated by RegCo Technologies Limited','FIRS WHT Return — May 2026'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','ready','CIT Return',NOW()-INTERVAL '20 days',true,null,null,null,'RegCo_CIT_2025.txt',
'FIRS CIT RETURN — 2025
NAKDNX MFB LIMITED
=======================================
Net Assessable Profit: NGN 184,300,000
CIT (30%): NGN 55,290,000
Education Tax: NGN 4,607,500
TOTAL TAX PAYABLE: NGN 59,897,500
=======================================
Generated by RegCo Technologies Limited','FIRS CIT Return — 2025'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','ready','Single Obligor Report',NOW()-INTERVAL '12 days',true,null,null,null,'RegCo_SingleObligor_Q1_2026.txt',
'NDIC SINGLE OBLIGOR REPORT — Q1 2026
NAKDNX MFB LIMITED
=======================================
Capital Base: NGN 160,000,000
Single Obligor Limit (5%): NGN 8,000,000
Largest exposure: NGN 13,500,000 (8.4% — WATCH LIST)
=======================================
Generated by RegCo Technologies Limited','NDIC Single Obligor Report — Q1 2026'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','pending','Monetary Policy Return',null,false,null,null,null,null,null,'CBN Monetary Policy Return — Pending'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','failed','NFIU Regulatory Return',NOW()-INTERVAL '1 day',false,null,null,null,null,null,'NFIU Regulatory Return — Failed');

INSERT INTO public.transaction_reviews (user_id, upload_batch_id, transaction_date, account_number, customer_name, amount, flag_type, flag_reason, flag_severity, review_status, channel)
VALUES
('ea7dd158-eba4-4848-9caa-d787c187d8be','demo_001',NOW()-INTERVAL '3 days','0123456789','Emeka Okafor Enterprises',6500000,'CTR','Transaction of NGN 6,500,000 meets CBN CTR threshold of NGN 5,000,000.','critical','pending','mobile'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','demo_001',NOW()-INTERVAL '3 days','0987654321','Fatima Al-Hassan Trading',4750000,'STRUCTURING','NGN 250,000 below CTR threshold. Possible structuring.','high','pending','branch'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','demo_001',NOW()-INTERVAL '4 days','0556677889','Aisha Musa Ibrahim',12000000,'VELOCITY','NGN 12M in 24 hours exceeds velocity threshold.','critical','escalated','mobile'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','demo_001',NOW()-INTERVAL '4 days','0112233445','Chukwudi Obi Logistics',3000000,'ROUND_FIGURE','Exact round NGN 3,000,000 with vague narration.','medium','cleared','transfer');

INSERT INTO public.audit_issues (user_id, issue_ref, source, category, title, description, severity, status, owner_name, due_date, remediation_plan, examination_date, regulator)
VALUES
('ea7dd158-eba4-4848-9caa-d787c187d8be','CBN-2026-001','CBN Examination','KYC','Incomplete KYC for 23 high-value customers','23 customers with balances above NGN 5M have incomplete KYC.','high','in_progress','Marvellous Okoroigwe',CURRENT_DATE+INTERVAL '18 days','Contact all 23 customers; update records within 30 days.','2026-04-15','CBN'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','CBN-2026-002','CBN Examination','AML/CFT','AML/CFT policy not reviewed in 12 months','Policy last reviewed March 2025. CBN requires annual board-level review.','medium','open','Marvellous Okoroigwe',CURRENT_DATE+INTERVAL '7 days','Schedule board meeting; update policy; obtain signed approval.','2026-04-15','CBN'),
('ea7dd158-eba4-4848-9caa-d787c187d8be','INT-2026-001','Internal Audit','Governance','Transaction monitoring system not tested quarterly','No documentation of Q3/Q4 2025 TMS tests.','low','remediated','Marvellous Okoroigwe',CURRENT_DATE-INTERVAL '5 days','Q1 2026 test completed.','2026-03-01','Internal');

DO $$
DECLARE m TEXT := TO_CHAR(NOW(),'YYYY-MM');
BEGIN
  INSERT INTO public.monthly_compliance_tasks (user_id,month,category,title,description,priority,status,priority_order) VALUES
  ('ea7dd158-eba4-4848-9caa-d787c187d8be',m,'Regulatory Returns','File CBN MFB Regulatory Return','Monthly balance sheet to CBN.','high','completed',1),
  ('ea7dd158-eba4-4848-9caa-d787c187d8be',m,'Regulatory Returns','File PAYE Remittance — FIRS','Employee PAYE to FIRS by 10th.','high','completed',2),
  ('ea7dd158-eba4-4848-9caa-d787c187d8be',m,'Regulatory Returns','File VAT Return — FIRS','Monthly VAT at 7.5%.','high','completed',3),
  ('ea7dd158-eba4-4848-9caa-d787c187d8be',m,'Regulatory Returns','File WHT Return — FIRS','WHT on vendor payments.','high','pending',4),
  ('ea7dd158-eba4-4848-9caa-d787c187d8be',m,'AML Monitoring','Review 4 pending AML flags','2 critical flags require immediate action.','high','pending',5),
  ('ea7dd158-eba4-4848-9caa-d787c187d8be',m,'AML Monitoring','Screen new customers — sanctions','47 new customers need screening.','high','pending',6),
  ('ea7dd158-eba4-4848-9caa-d787c187d8be',m,'KYC Compliance','Remediate 23 incomplete KYC files','CBN finding CBN-2026-001.','medium','in_progress',7),
  ('ea7dd158-eba4-4848-9caa-d787c187d8be',m,'Regulatory Monitoring','Review CBN circulars','Check Regulatory Intelligence.','medium','completed',8),
  ('ea7dd158-eba4-4848-9caa-d787c187d8be',m,'Reporting','Generate monthly board pack','Use Board Pack page.','medium','pending',9),
  ('ea7dd158-eba4-4848-9caa-d787c187d8be',m,'Audit','Resolve CBN-2026-002 AML policy finding','Board meeting before 7-day deadline.','high','in_progress',10);
END $$;

INSERT INTO public.compliance_reports (user_id,month,status,generated_at,content,metrics)
VALUES ('ea7dd158-eba4-4848-9caa-d787c187d8be',TO_CHAR(NOW()-INTERVAL '1 month','YYYY-MM'),'ready',NOW()-INTERVAL '5 days',
'NAKDNX MICROFINANCE BANK LIMITED
MONTHLY COMPLIANCE COMMITTEE REPORT — APRIL 2026
=====================================================
Returns Filed: 8/8
AML Flags: 4 (1 critical, 2 high, 1 medium)
STRs Filed: 1
KYC Rate: 87%
Customers Screened: 23
Tasks: 8/10 completed
=====================================================
Generated by RegCo Technologies Limited',
'{"reportsReady":8,"reportsFailed":0,"criticalFlags":1,"strEscalated":1,"kycRate":87,"screenings":23}'::jsonb);